#include "PORTS_INIT.h"
void init(uint8_t number)
	{
		 switch(number){
			 
			 case PORTA:
	SYSCTL_RCGCGPIO_R |= 0X01 ; // ENABLE CLOCK FOR PORT A
		while((SYSCTL_PRGPIO_R&0x00000001) == 0){};
	GPIO_PORTA_AFSEL_R |= 0x03 ;    // SET A0 AND A1 TO USE AS UART0
  GPIO_PORTA_AFSEL_R &= ~0xFC ; 			// other pins GPIO 
	GPIO_PORTA_PCTL_R	|= 0x00000011 ;   //UART0 A0 & A1
  GPIO_PORTA_PCTL_R	&= ~0xFFFFFF00 ;  
	GPIO_PORTA_AMSEL_R &= ~0xFF ;
	GPIO_PORTA_DIR_R |= 0XFC ;	 // USE OTHER PINS AS OUTPUTS 
	
  GPIO_PORTA_DEN_R |= 0XFF ;		
	GPIO_PORTA_LOCK_R = 0X4C4F434B ;	
	GPIO_PORTA_CR_R |= 0XFF ;		
				 break;
			 
			 case PORTB:
	SYSCTL_RCGCGPIO_R |= 0X02 ; // ENABLE CLOCK FOR PORT B
		while((SYSCTL_PRGPIO_R&0x00000020) == 0){};
	GPIO_PORTB_AFSEL_R &= ~0xFF ;   //no alternate function
  GPIO_PORTB_PCTL_R	&= ~0xFFFFFFFF ;
	GPIO_PORTB_AMSEL_R &= ~0XFF ;
	GPIO_PORTB_DIR_R |= 0XFF ;	
  GPIO_PORTB_DEN_R |= 0XFF ;		
	GPIO_PORTB_LOCK_R = 0X4C4F434B ;	
	GPIO_PORTB_CR_R |= 0XFF ;		
				 break;
			
			 case PORTF:
	SYSCTL_RCGCGPIO_R |= 0X20 ; // ENABLE CLOCK FOR PORT F
		while((SYSCTL_PRGPIO_R&0x00000020) == 0){};
	GPIO_PORTF_AFSEL_R &= ~0x1F ;   //no alternate function
  GPIO_PORTF_PCTL_R	&= ~0x000FFFFF ;
	GPIO_PORTF_AMSEL_R &= ~0X1F ;
	GPIO_PORTF_DIR_R |= 0X0E ;	// PF0 & PF 4 INPUT [SWITCHES] AND PF1,PF2,PF3 [LEDS] OUTPUT
  GPIO_PORTF_DEN_R |= 0X1F ;		
	GPIO_PORTF_LOCK_R = 0X4C4F434B ;	
	GPIO_PORTF_CR_R |= 0X1F ;		
	GPIO_PORTF_PUR_R |= 0X11 ;	//PULL UP RESISTORS FOR SWITCHES
  
				 break;
			
			 case PORTD:
	SYSCTL_RCGCGPIO_R |= 0X08 ; // ENABLE CLOCK FOR PORT D
		while((SYSCTL_PRGPIO_R&0x00000008) == 0){};
	GPIO_PORTD_AFSEL_R |= 0xC0 ;   //SET D7 & D6 AD UART2
  GPIO_PORTD_PCTL_R	|= 0x11000000 ;
	GPIO_PORTD_AMSEL_R &= ~0XC0 ;
  GPIO_PORTD_DEN_R |= 0XC0 ;		
	GPIO_PORTD_LOCK_R = 0X4C4F434B ;	
	GPIO_PORTD_CR_R |= 0XC0 ;	
break ;
			 default :
break ;				 
		 }	 
	 }